### ISSUE TITLE
The app keeps playing the ring tone even after I turn it off. 

### ISSUE THREAD

**Issue by aliar97** [442-location-alarm/location-alarm#6]
if you sent an alarm on a certain place and then go there, it plays the ringtone, but then when you try to turn it off it still plays the ring tone. I even tried deleting the location and it still keeps playing. This is definitely a major bug.

**Comment by maps101** [comment]
Thank you for finding this.

Upon investigation we found that this is actually caused in multiple places due to a series of passed and received intents. We were able to reliably fix the issue by having the notification stop the alarm, but were unable to find a robust fix to the issue of it not stopping when turning off or disabling the alarm in the time that we have. This is a major issue that would take more time than we had able to allow.

**Comment by jamesbmc** [comment]
Fix for tapping notification starting new ring/vibrate: https://github.com/442-location-alarm/location-alarm/commit/0ba4b99e4f681190cd58634d167bcea23259a055

Fix for vibrate: https://github.com/442-location-alarm/location-alarm/commit/6b2798fae06e27b9250509e1d425a4d597d9b7e2
