### ISSUE TITLE
No sound or vibration

### ISSUE THREAD

**Issue by s711258w** [442-location-alarm/location-alarm#8]
I set a location to where I am and input within 5 mile radius, but when I set Sound and Vibrate and save it, I just get a short notification sound with no alarm or vibration. When I first opened the app and set a location there was an alarm sound, but vibrate has not been working at all.  Something is wrong when setting locations repeatedly, alarm only works on the first couple changes. This is a major bug.

**Comment by jamesbmc** [comment]
https://stackoverflow.com/questions/22437159/addproximityalert-not-working

As a note, this has been one of the biggest bugs throughout the last few days that we have been unable to consistently reproduce or fix (despite multiple attempts).

We believe this is a well-known problem with the location manager that has no current fix. Since we cannot consistently reproduce the bug and there is no relevant error message, I do not believe we will be able to solve this problem in one day. An alternative could be completely replacing the location manager with another service that handles proximity alerts. However, we would need to find a replacement that does what we need, read the documentation, implement it, and then exhaustively test to make sure that the same issue does not happen (or any other issues).
